#!/usr/bin/env bash
# Verify PDF requirements vs. codebase state.
set -u

PASS=0; FAIL=0; SKIP_HOME=0

check() {
  local label="$1"; local file="$2"; local pattern="$3"
  if [ ! -f "$file" ]; then
    echo "❌ MISSING FILE: $file"
    FAIL=$((FAIL+1)); return
  fi
  if grep -q -- "$pattern" "$file" 2>/dev/null; then
    echo "✅ $label"
    PASS=$((PASS+1))
  else
    echo "❌ $label  (pattern not found in $file)"
    FAIL=$((FAIL+1))
  fi
}

SITEDATA="/home/z/my-project/src/lib/site-data.ts"
SVCSDATA="/home/z/my-project/src/lib/services-data.ts"
HOMEPAGE="/home/z/my-project/src/app/page.tsx"
SOLSECTION="/home/z/my-project/src/components/site/solutions-section.tsx"

echo "============================================================"
echo "1. /services/enterprise-web-solutions"
echo "============================================================"
check "Hero: 'Collaborating for Business Excellence'" "$SVCSDATA" "Collaborating for Business Excellence"
check "Tagline: 'Collaborating for Business Excellence'" "$SVCSDATA" "tagline: \"Collaborating for Business Excellence\""
check "Para 1: 'Enterprise applications are the foundation'" "$SVCSDATA" "Enterprise applications are the foundation"
check "Para 2: 'By bringing together industry expertise'" "$SVCSDATA" "By bringing together industry expertise"
check "CapabilitiesTiles intro eyebrow 'Our Web Solutions'" "$SVCSDATA" "eyebrow: \"Our Web Solutions\""
check "Tile: 'Enterprise Web Applications'" "$SVCSDATA" "Enterprise Web Applications"
check "Tile: 'Corporate Websites'" "$SVCSDATA" "Corporate Websites"
check "Tile: 'SaaS Platforms'" "$SVCSDATA" "SaaS Platforms"
check "Tile: 'Customer Portals'" "$SVCSDATA" "Customer Portals"
check "Tile: 'B2B Platforms'" "$SVCSDATA" "B2B Platforms"
check "Tile: 'B2C Platforms'" "$SVCSDATA" "B2C Platforms"
check "Tile: 'Progressive Web Applications'" "$SVCSDATA" "Progressive Web Applications"
check "Tile: 'Headless Architecture'" "$SVCSDATA" "Headless Architecture"
check "Tile: 'API-Driven Applications'" "$SVCSDATA" "API-Driven Applications"
check "Tile: 'CMS Development'" "$SVCSDATA" "CMS Development"
check "Tile: 'Web Application Modernization'" "$SVCSDATA" "Web Application Modernization"
check "Closing quote" "$SVCSDATA" "Build Digital Experiences That Move the Enterprise."

echo ""
echo "============================================================"
echo "2. /industries/cybersecurity"
echo "============================================================"
check "Hero heading: 'Cybersecurity for Business Resilience'" "$SITEDATA" "Cybersecurity for Business Resilience"
check "Intro para: 'As digital ecosystems continue to expand'" "$SITEDATA" "As digital ecosystems continue to expand"
check "Solutions eyebrow: 'Our Services, Designed Around Your Business'" "$SITEDATA" "Our Services, Designed Around Your Business"
check "Solutions lead: 'Strengthen your organization'" "$SITEDATA" "Strengthen your organization with a comprehensive portfolio"
check "Closing quote" "$SITEDATA" "Resilience by Design. Security by Default."

echo ""
echo "============================================================"
echo "3. /industries/ecommerce"
echo "============================================================"
check "Hero heading: 'Navigating the Future of Retail 4.0'" "$SITEDATA" "Navigating the Future of Retail 4.0"
check "Tagline: 'Automation. Experience-led retail. Data-driven intelligence.'" "$SITEDATA" "Automation. Experience-led retail. Data-driven intelligence."
check "Solutions eyebrow: 'Powering the Future of Retail'" "$SITEDATA" "Powering the Future of Retail"
check "Solutions lead: 'Transform every aspect of your retail business'" "$SITEDATA" "Transform every aspect of your retail business"
check "Tile 1: Digital Commerce" "$SITEDATA" "title: \"Digital Commerce\""
check "Tile 2: Customer Experience" "$SITEDATA" "title: \"Customer Experience\""
check "Tile 3: Retail Analytics & AI" "$SITEDATA" "title: \"Retail Analytics & AI\""
check "Tile 4: Supply Chain & Inventory" "$SITEDATA" "title: \"Supply Chain & Inventory\""
check "Tile 5: Store Operations" "$SITEDATA" "title: \"Store Operations\""
check "Tile 6: Retail ERP & Business Applications" "$SITEDATA" "Retail ERP & Business Applications"
check "Tile 7: Product & Merchandising" "$SITEDATA" "Product & Merchandising"
check "Tile 8: Cloud & Digital Transformation" "$SITEDATA" "Cloud & Digital Transformation"
check "Closing quote" "$SITEDATA" "Build Agile, Resilient, Future-Ready Retail."

echo ""
echo "============================================================"
echo "4. /industries/logistics"
echo "============================================================"
check "Hero heading: 'Accelerating Digital Transformation'" "$SITEDATA" "Accelerating Digital Transformation"
check "Intro: 'We combine deep industry understanding'" "$SITEDATA" "We combine deep industry understanding"
check "Overview quote: 'Transform Today. Lead Tomorrow.'" "$SITEDATA" "Transform Today. Lead Tomorrow."
check "Solutions eyebrow: 'Powering the Next Generation of Travel, Transportation & Hospitality'" "$SITEDATA" "Powering the Next Generation of Travel, Transportation & Hospitality"
check "Hospitality section heading: 'Hospitality Designed Around Every Guest'" "$SITEDATA" "Hospitality Designed Around Every Guest"
check "Logistics section heading: 'Logistics Built for Seamless Movement'" "$SITEDATA" "Logistics Built for Seamless Movement"
check "Closing quote" "$SITEDATA" "Move People. Move Goods. Move Forward."

echo ""
echo "============================================================"
echo "5. /industries/healthcare"
echo "============================================================"
check "Hero heading: 'Technology Advancing the Future of Healthcare'" "$SITEDATA" "Technology Advancing the Future of Healthcare"
check "Overview section heading" "$SITEDATA" "heading: \"Overview\""
check "Intro para: 'Healthcare is evolving rapidly'" "$SITEDATA" "Healthcare is evolving rapidly"
check "Para: 'Technology is reshaping'" "$SITEDATA" "Technology is reshaping how healthcare is delivered"
check "Para: 'Innovations such as AI-powered diagnostics'" "$SITEDATA" "Innovations such as AI-powered diagnostics"
check "Para: 'At the same time, healthcare organizations'" "$SITEDATA" "At the same time, healthcare organizations"
check "Para: 'We help healthcare organizations modernize'" "$SITEDATA" "We help healthcare organizations modernize"
check "Overview quote: 'Transform Healthcare. Empower People. Improve Outcomes.'" "$SITEDATA" "Transform Healthcare. Empower People. Improve Outcomes."
check "Solutions eyebrow: 'Powering Healthcare Transformation'" "$SITEDATA" "Powering Healthcare Transformation"
check "Tile 1: Elevate Patient Experiences" "$SITEDATA" "Elevate Patient Experiences"
check "Tile 2: Modernize Healthcare Operations" "$SITEDATA" "Modernize Healthcare Operations"
check "Tile 3: Strengthen Compliance & Security" "$SITEDATA" "Strengthen Compliance & Security"
check "Tile 4: Connect the Healthcare Ecosystem" "$SITEDATA" "Connect the Healthcare Ecosystem"
check "Tile 5: Accelerate Innovation at Scale" "$SITEDATA" "Accelerate Innovation at Scale"
check "Closing quote: 'Reimagine Healthcare. Transform Experiences. Create Lasting Impact.'" "$SITEDATA" "Reimagine Healthcare. Transform Experiences. Create Lasting Impact."

echo ""
echo "============================================================"
echo "6. /services/ai-automation"
echo "============================================================"
check "Hero heading: 'AI-Powered Automation for Smarter Operations'" "$SVCSDATA" "AI-Powered Automation for Smarter Operations"
check "Tagline: 'Automate Processes. Augment Intelligence. Accelerate Growth.'" "$SVCSDATA" "Automate Processes. Augment Intelligence. Accelerate Growth."
check "Intro 1: 'AI is transforming automation from rule-based'" "$SVCSDATA" "AI is transforming automation from rule-based"
check "Intro 2: 'We help enterprises identify high-value automation'" "$SVCSDATA" "We help enterprises identify high-value automation"
check "CapabilitiesTiles eyebrow: 'Our AI Automation Capabilities'" "$SVCSDATA" "Our AI Automation Capabilities"
check "Tile 1: Intelligent Process Automation" "$SVCSDATA" "Intelligent Process Automation"
check "Tile 2: AI-Powered Document Processing" "$SVCSDATA" "AI-Powered Document Processing"
check "Tile 3: Generative AI Automation" "$SVCSDATA" "Generative AI Automation"
check "Tile 4: Agentic AI" "$SVCSDATA" "title: \"Agentic AI\""
check "Tile 5: Customer Service Automation" "$SVCSDATA" "Customer Service Automation"
check "Tile 6: Business Workflow Automation" "$SVCSDATA" "Business Workflow Automation"
check "Tile 7: Intelligent Decision Support" "$SVCSDATA" "Intelligent Decision Support"
check "Tile 8: AI-Driven Operations" "$SVCSDATA" "AI-Driven Operations"
check "'From Automation to Autonomous Operations' section title" "$SVCSDATA" "From Automation to Autonomous Operations"
check "Closing quote: 'Transform Workflows. Empower People. Accelerate Business.'" "$SVCSDATA" "Transform Workflows. Empower People. Accelerate Business."

echo ""
echo "============================================================"
echo "7. HOME PAGE — 'AI Technologies for Business Transformation'"
echo "============================================================"
# The home page imports AISection from a separate component file, so check both.
AISECTION="/home/z/my-project/src/components/site/ai-section.tsx"
check "Home page imports AISection component" "$HOMEPAGE" "AISection"
check "AISection component file exists" "$AISECTION" "export function AISection"
check "'AI Technologies for Business Transformation' label" "$AISECTION" "AI Technologies for Business Transformation"
check "'AI That Drives Business Impact' headline" "$AISECTION" "AI That Drives"
check "Intro para: 'Accelerate your AI and Generative AI journey'" "$AISECTION" "Accelerate your AI and Generative AI journey"
check "'Welcome to AI That Creates Business Value' subtitle" "$AISECTION" "Welcome to AI That Creates"
check "Para: 'The true potential of AI lies not simply'" "$AISECTION" "The true potential of AI lies not simply"
check "Para: 'We help enterprises move from AI experimentation'" "$AISECTION" "We help enterprises move from AI experimentation"
check "Para: 'From Generative AI and Agentic AI'" "$AISECTION" "From Generative AI and Agentic AI"
check "Para: 'Our focus is simple: turn AI from an emerging'" "$AISECTION" "Our focus is simple: turn AI"
check "Closing tagline: 'From AI Potential to Business Impact.'" "$AISECTION" "From AI Potential to"
check "AI image embedded" "$AISECTION" "src=\"/images/ai/ai-hero.png\""

echo ""
echo "============================================================"
echo "8. HCL-tech design pattern (SolutionsSection component)"
echo "============================================================"
check "SolutionsSection component file exists" "$SOLSECTION" "export function SolutionsSection"
check "OverviewQuote component exists" "$SOLSECTION" "export function OverviewQuote"
check "Tile grid responsive (sm:grid-cols-2)" "$SOLSECTION" "sm:grid-cols-2"
check "Closing quote band on dark navy" "$SOLSECTION" "closingBg"
check "Card-lift hover on tiles" "$SOLSECTION" "card-lift"

echo ""
echo "============================================================"
echo "RESULT"
echo "============================================================"
echo "PASS: $PASS"
echo "FAIL: $FAIL"
