import type { Metadata } from "next";
import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import Image from "next/image";
import { ArrowRight, type LucideIcon } from "lucide-react";
import { PageHero, type PageHeroVariant } from "@/components/site/page-hero";
import { Reveal, SectionHeading } from "@/components/site/primitives";
import { buildMetadata } from "@/lib/seo";
import { industries, type Industry } from "@/lib/site-data";

/* ============================================================
 * Dynamic industry detail page — handles all 7 industry slugs.
 * Layout picks by slug:
 *
 *   A (financial-services — kept AS-IS per user request)
 *      2-col sticky intro + offset-cream framed bannerImage →
 *      4-col KPI / stage cards (flow / workflow) →
 *      alternating full-width narrative sections →
 *      ink-navy glass cards (subIndustries / techEnablers).
 *
 *   B (healthcare · education · logistics · cybersecurity ·
 *      ecommerce · automation — clean editorial template)
 *      §1 white 2-col: intro text (eyebrow + heading +
 *        paragraph + focusAreas line + GlobalReachBadge) +
 *        offset-cream framed bannerImage.
 *      §2 alternating bg-shade / bg-white: ind.sections as
 *        paragraph-only prose blocks (heading + paragraphs +
 *        optional image — NO bullets, NO lists). Falls back to
 *        intro + tagline prose when ind.sections is empty.
 *      §3 white: cards grid (subIndustries → pillars →
 *        platformFeatures → layers → channels → flow →
 *        workflow → journey fallback chain) — icon tile +
 *        title + paragraph desc, NO bullets.
 *      §4 full-width banner image break with navy gradient
 *        overlay + tagline quote.
 *
 * No CTABand / CTAStrip / "Other industries" footer — every
 * layout ends cleanly on its last section.
 * ============================================================ */

export function generateStaticParams() {
  return industries.map((i) => ({ slug: i.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const ind = industries.find((i) => i.slug === slug);
  if (!ind) return {};
  const title = `${ind.title} | Globantis Labs`;
  const description =
    ind.intro ??
    ind.heroHeading ??
    ind.sections?.[0]?.paragraphs?.[0] ??
    ind.tagline ??
    ind.title;
  return buildMetadata({
    title,
    description,
    path: `/industries/${slug}`,
    keywords: [ind.title, ind.tagline, ...(ind.focusAreas ?? [])].filter(
      Boolean
    ) as string[],
  });
}

/* ============================================================
 * Per-industry hero variant assignment (matches the layout plan
 * fingerprints in layout_registry.json / layout-plans/*.json,
 * generated by scripts/pick_layout.py — see it-page-designer skill).
 * All 5 variants now have supporting data (Industry type gained
 * `partners` and `challenges` fields) so no fallbacks remain.
 * ============================================================ */
const HERO_VARIANTS: Record<string, PageHeroVariant> = {
  "financial-services": "diagonal-crop",
  healthcare: "centered-logo-strip",
  education: "split-image-left",
  logistics: "split-image-right",
  cybersecurity: "diagonal-crop",
  ecommerce: "centered-logo-strip",
  automation: "split-image-left",
};

/* Per-industry §1 challenges section variant (from layout plan). */
type ChallengesVariant = "cards-icons" | "split-photo" | "stat-led";
const CHALLENGES_VARIANTS: Record<string, ChallengesVariant> = {
  "financial-services": "cards-icons",
  healthcare: "cards-icons",
  education: "split-photo",
  logistics: "split-photo",
  cybersecurity: "cards-icons",
  ecommerce: "split-photo",
  automation: "cards-icons",
};

export default async function IndustryDetailPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const ind = industries.find((i) => i.slug === slug);
  if (!ind) notFound();

  const layout = slug === "financial-services" ? "A" : "B";
  const heroVariant: PageHeroVariant = HERO_VARIANTS[slug] ?? "fullbleed-overlay";
  const challengesVariant: ChallengesVariant =
    CHALLENGES_VARIANTS[slug] ?? "cards-icons";

  // Description shows on split / diagonal / centered variants — pull
  // the most informative one-liner available on the Industry object.
  const heroDescription =
    heroVariant !== "fullbleed-overlay"
      ? ind.intro ?? ind.tagline
      : undefined;

  return (
    <>
      <PageHero
        title={ind.title}
        label={ind.label ?? ind.title}
        image={ind.bannerImage}
        variant={heroVariant}
        description={heroDescription}
        partners={ind.partners}
        primaryCta={{ label: "Start a project", href: "/contact" }}
        secondaryCta={{ label: "View case studies", href: "/case-studies" }}
        crumbs={[
          { label: "Home", href: "/" },
          { label: "Industries", href: "/industries" },
          { label: ind.title },
        ]}
      />
      {layout === "A" && <LayoutA ind={ind} />}
      {layout === "B" && (
        <LayoutB
          ind={ind}
          challengesVariant={challengesVariant}
        />
      )}
    </>
  );
}

/* ============================================================
 * Shared — Global reach badge
 * Woven into the intro of every layout so the UK, Canada, Dubai
 * reach is visible without dominating the page.
 * ============================================================ */
function GlobalReachBadge({ className }: { className?: string }) {
  return (
    <div className={className}>
      <span className="inline-flex items-center gap-2 rounded-full border border-brand/30 bg-cream px-3.5 py-2 text-xs font-semibold text-brand">
        <span aria-hidden className="size-1.5 rounded-full bg-flame" />
        Serving clients across the UK, Canada, Dubai, and beyond
      </span>
    </div>
  );
}

/* ============================================================

/* ============================================================
 * Shared — narrative section renderer
 * Renders one ind.sections[] block with eyebrow + flame rule +
 * heading + paragraphs + optional image. Used by all layouts
 * so the prose voice stays consistent while each layout owns
 * its surrounding section bg.
 * ============================================================ */
function NarrativeSection({
  sec,
  bg,
  image,
  imageSide = "right",
}: {
  sec: NonNullable<Industry["sections"]>[number];
  bg: "bg-white" | "bg-shade";
  image?: string;
  imageSide?: "left" | "right";
}) {
  const useImage = sec.image || image;
  return (
    <section className={`${bg} py-section-md`}>
      <div className="container-site">
        <div className={`grid gap-12 lg:gap-16 ${useImage ? "lg:grid-cols-2 lg:items-center" : "mx-auto max-w-4xl"}`}>
          {/* Text side */}
          <div className={imageSide === "left" && useImage ? "lg:order-2" : ""}>
            <Reveal>
              {sec.label && <span className="section-label">[ {sec.label} ]</span>}
              <div aria-hidden className="rule-flame mb-6" />
              <h3 className="text-display-md font-bold leading-snug text-ink">
                {sec.heading}
              </h3>
              <div className="mt-5 space-y-4">
                {sec.paragraphs?.map((p, j) => (
                  <p key={j} className="text-[16px] leading-relaxed text-body">
                    {p}
                  </p>
                ))}
              </div>
            </Reveal>
          </div>
          {/* Image side */}
          {useImage && (
            <Reveal delay={0.1} className={imageSide === "left" ? "lg:order-1" : ""}>
              <div className="relative">
                <div
                  aria-hidden
                  className={`absolute hidden h-full w-full rounded-2xl border border-line bg-cream lg:block ${
                    imageSide === "left" ? "-left-5 -top-5" : "-right-5 -top-5"
                  }`}
                />
                <div className="relative overflow-hidden rounded-2xl shadow-float">
                  <Image
                    src={useImage}
                    alt={sec.heading}
                    width={640}
                    height={480}
                    className="h-full w-full object-cover"
                  />
                </div>
              </div>
            </Reveal>
          )}
        </div>
      </div>
    </section>
  );
}

/* ============================================================
 * Challenges section — replaces the old text-only §1 intro
 * with real industry pain-point data. Three variants per
 * it-page-designer skill Appendix A:
 *   - cards-icons   : 3-4 problem cards in a grid with icon tile
 *   - split-photo   : full-width photo + numbered challenge list
 *   - stat-led      : each challenge paired with an industry stat
 *                     (falls back to cards-icons when no stats)
 * ============================================================ */
function ChallengesSection({
  challenges,
  variant,
  image,
}: {
  challenges: NonNullable<Industry["challenges"]>;
  variant: "cards-icons" | "split-photo" | "stat-led";
  image?: string;
}) {
  if (challenges.length === 0) return null;

  /* ---------- Variant: cards-icons ---------- */
  if (variant === "cards-icons") {
    return (
      <section className="bg-white py-section-md">
        <div className="container-site">
          <Reveal>
            <SectionHeading
              label="[ The challenges ]"
              title={
                <>
                  What the industry is{" "}
                  <span className="text-flame">up against.</span>
                </>
              }
              lead="Real pain-points our clients name first — and the shape of the work needed to move past them."
              align="center"
            />
          </Reveal>
          <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {challenges.map((c, i) => {
              const Icon = c.icon;
              return (
                <Reveal key={c.title} delay={Math.min(i * 0.06, 0.3)}>
                  <div className="card-lift relative flex h-full flex-col rounded-2xl border border-line bg-shade p-6 hover:border-flame/40 hover:shadow-lift">
                    <div className="flex items-center justify-between">
                      {Icon && (
                        <span className="flex size-11 items-center justify-center rounded-lg border border-brand/20 bg-white text-brand">
                          <Icon aria-hidden className="size-5" />
                        </span>
                      )}
                      <span className="font-mono text-xs font-semibold tracking-[0.12em] text-ink/40">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                    </div>
                    <p className="mt-5 text-base font-bold text-ink">
                      {c.title}
                    </p>
                    <p className="mt-2 text-sm leading-relaxed text-body">
                      {c.desc}
                    </p>
                  </div>
                </Reveal>
              );
            })}
          </div>
        </div>
      </section>
    );
  }

  /* ---------- Variant: split-photo ---------- */
  if (variant === "split-photo") {
    return (
      <section className="bg-white py-section-md">
        <div className="container-site">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center lg:gap-16">
            {/* Left — photo */}
            {image && (
              <Reveal>
                <div className="relative">
                  <div
                    aria-hidden
                    className="absolute -left-5 -top-5 hidden h-full w-full rounded-2xl border border-line bg-cream lg:block"
                  />
                  <div className="relative overflow-hidden rounded-2xl border border-line bg-ink shadow-lift">
                    <Image
                      src={image}
                      alt="Industry environment"
                      width={720}
                      height={560}
                      sizes="(min-width: 1024px) 600px, 100vw"
                      className="h-[320px] w-full object-cover sm:h-[420px] lg:h-[520px]"
                    />
                    <div
                      aria-hidden
                      className="absolute inset-x-0 bottom-0 h-24"
                      style={{
                        background:
                          "linear-gradient(to top, rgba(0,3,61,0.55) 0%, rgba(0,3,61,0) 100%)",
                      }}
                    />
                  </div>
                </div>
              </Reveal>
            )}

            {/* Right — numbered challenge list */}
            <div className={image ? "" : "lg:col-span-2"}>
              <Reveal>
                <span className="section-label">[ The challenges ]</span>
                <div aria-hidden className="rule-flame mt-3 mb-6" />
                <h2 className="text-display-md font-bold leading-snug text-ink">
                  What the industry is{" "}
                  <span className="text-flame">up against.</span>
                </h2>
                <ul className="mt-7 space-y-6">
                  {challenges.map((c, i) => {
                    const Icon = c.icon;
                    return (
                      <li key={c.title} className="flex gap-5">
                        <div className="flex flex-col items-center">
                          <span className="flex size-11 shrink-0 items-center justify-center rounded-lg border border-brand/20 bg-cream text-brand">
                            {Icon ? (
                              <Icon aria-hidden className="size-5" />
                            ) : null}
                          </span>
                          {i < challenges.length - 1 && (
                            <span
                              aria-hidden
                              className="mt-2 w-px flex-1 bg-line"
                            />
                          )}
                        </div>
                        <div className="pb-2">
                          <p className="text-base font-bold text-ink">
                            <span className="font-mono text-xs font-semibold tracking-[0.12em] text-flame">
                              {String(i + 1).padStart(2, "0")} —{" "}
                            </span>
                            {c.title}
                          </p>
                          <p className="mt-1.5 text-sm leading-relaxed text-body">
                            {c.desc}
                          </p>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </Reveal>
            </div>
          </div>
        </div>
      </section>
    );
  }

  /* ---------- Variant: stat-led (no stats in data yet → fall back to
   *  cards-icons but with the full-bleed banner photo treatment so
   *  the page still reads differently from sibling industries) ---- */
  return (
    <section className="bg-shade py-section-md">
      <div className="container-site">
        <Reveal>
          <SectionHeading
            label="[ The challenges ]"
            title={
              <>
                What the industry is{" "}
                <span className="text-flame">up against.</span>
              </>
            }
            lead="Real pain-points our clients name first — and the shape of the work needed to move past them."
            align="center"
          />
        </Reveal>
        <div className="mt-12 grid gap-5 md:grid-cols-2">
          {challenges.map((c, i) => {
            const Icon = c.icon;
            return (
              <Reveal key={c.title} delay={Math.min(i * 0.06, 0.3)}>
                <div className="card-lift relative flex h-full items-start gap-5 rounded-2xl border border-line bg-white p-6 hover:border-flame/40 hover:shadow-lift">
                  {Icon && (
                    <span className="flex size-12 shrink-0 items-center justify-center rounded-lg border border-brand/20 bg-cream text-brand">
                      <Icon aria-hidden className="size-6" />
                    </span>
                  )}
                  <div>
                    <p className="text-base font-bold text-ink">
                      <span className="font-mono text-xs font-semibold tracking-[0.12em] text-flame">
                        {String(i + 1).padStart(2, "0")} —{" "}
                      </span>
                      {c.title}
                    </p>
                    <p className="mt-1.5 text-sm leading-relaxed text-body">
                      {c.desc}
                    </p>
                  </div>
                </div>
              </Reveal>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ============================================================
 * IndustryShowcase — renders the unique per-industry showcase
 * module. Each industry has its OWN data shape (pillars, journey,
 * pathway, flow, layers, channels, workflow, etc.) and gets a
 * visually-distinct section no sibling industry renders. This is
 * the single biggest reason every industry page reads differently.
 * ============================================================ */
function IndustryShowcase({ ind }: { ind: Industry }) {
  switch (ind.slug) {
    case "healthcare":
      return <HealthcareShowcase ind={ind} />;
    case "education":
      return <EducationShowcase ind={ind} />;
    case "logistics":
      return <LogisticsShowcase ind={ind} />;
    case "cybersecurity":
      return <CybersecurityShowcase ind={ind} />;
    case "ecommerce":
      return <EcommerceShowcase ind={ind} />;
    case "automation":
      return <AutomationShowcase ind={ind} />;
    default:
      return null;
  }
}

/* ---------- Healthcare: care pillars (4-card grid) + patient journey
 *  horizontal strip. Warm, caring visual: cream bg, large icon tiles,
 *  rounded cards. ---------- */
function HealthcareShowcase({ ind }: { ind: Industry }) {
  if (!ind.pillars && !ind.journey) return null;
  return (
    <>
      {ind.pillars && ind.pillars.length > 0 && (
        <section className="bg-cream py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ Care pillars ]"
                title={
                  <>
                    Four pillars of{" "}
                    <span className="text-flame">modern care.</span>
                  </>
                }
                lead="How we structure every healthcare engagement — from PHI security to last-mile access."
                align="center"
              />
            </Reveal>
            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {ind.pillars.map((p, i) => {
                const Icon = p.icon;
                return (
                  <Reveal key={p.title} delay={Math.min(i * 0.06, 0.3)}>
                    <div className="card-lift group relative h-full overflow-hidden rounded-3xl border border-line bg-white p-7 hover:border-flame/40 hover:shadow-lift">
                      {/* Flame top-bar on hover */}
                      <div
                        aria-hidden
                        className="absolute inset-x-0 top-0 h-1 origin-left scale-x-0 bg-gradient-to-r from-flame to-flame-soft transition-transform duration-300 group-hover:scale-x-100"
                      />
                      {Icon && (
                        <span className="flex size-14 items-center justify-center rounded-2xl border border-brand/20 bg-cream text-brand transition-colors group-hover:bg-flame group-hover:text-white">
                          <Icon aria-hidden className="size-7" />
                        </span>
                      )}
                      <p className="mt-5 text-lg font-bold text-ink">
                        {p.title}
                      </p>
                      <p className="mt-2 text-sm leading-relaxed text-body">
                        {p.desc}
                      </p>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {ind.journey && ind.journey.length > 0 && (
        <section className="bg-white py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ Patient journey ]"
                title={
                  <>
                    From schedule to{" "}
                    <span className="text-flame">follow-up.</span>
                  </>
                }
                lead="Every touchpoint in the patient journey — instrumented, observable, recoverable."
                align="center"
              />
            </Reveal>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {ind.journey.map((j, i) => {
                const Icon = j.icon;
                return (
                  <Reveal key={j.title} delay={Math.min(i * 0.06, 0.3)}>
                    <div className="relative h-full rounded-2xl border border-line bg-shade p-6">
                      <div className="flex items-center justify-between">
                        {Icon && (
                          <span className="flex size-10 items-center justify-center rounded-lg bg-flame/10 text-flame">
                            <Icon aria-hidden className="size-5" />
                          </span>
                        )}
                        <span className="font-mono text-xs font-bold tracking-[0.12em] text-ink/40">
                          STEP {String(i + 1).padStart(2, "0")}
                        </span>
                      </div>
                      <p className="mt-4 text-base font-bold text-ink">
                        {j.title}
                      </p>
                      <p className="mt-1 text-xs leading-relaxed text-body">
                        {j.desc}
                      </p>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>
      )}
    </>
  );
}

/* ---------- Education: 5-step numbered pathway (left sticky intro +
 *  right vertical stepper) + platform features 3-col grid. ---------- */
function EducationShowcase({ ind }: { ind: Industry }) {
  if (!ind.pathway && !ind.platformFeatures) return null;
  return (
    <>
      {ind.pathway && ind.pathway.length > 0 && (
        <section className="bg-shade py-section-md">
          <div className="container-site">
            <div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-start lg:gap-16">
              {/* Left — sticky intro */}
              <div className="lg:sticky lg:top-32 lg:self-start">
                <Reveal>
                  <span className="section-label">[ Learning pathway ]</span>
                  <div aria-hidden className="rule-flame mt-3 mb-6" />
                  <h2 className="text-display-md font-bold leading-snug text-ink">
                    Five steps to{" "}
                    <span className="text-flame">mastery.</span>
                  </h2>
                  <p className="mt-5 text-[16px] leading-relaxed text-body">
                    A repeatable learning pathway that adapts to each learner — from first diagnostic to capstone assessment.
                  </p>
                </Reveal>
              </div>
              {/* Right — vertical numbered pathway */}
              <div>
                <ol className="relative space-y-6 before:absolute before:left-[27px] before:top-2 before:h-[calc(100%-1rem)] before:w-px before:bg-line">
                  {ind.pathway.map((p, i) => (
                    <Reveal key={p.title} delay={Math.min(i * 0.05, 0.25)}>
                      <li className="relative flex gap-5">
                        <span className="flex size-14 shrink-0 items-center justify-center rounded-full border-2 border-flame bg-white font-mono text-lg font-bold text-flame">
                          {String(i + 1).padStart(2, "0")}
                        </span>
                        <div className="pt-1.5">
                          <p className="text-lg font-bold text-ink">
                            {p.title}
                          </p>
                          <p className="mt-1 text-sm leading-relaxed text-body">
                            {p.desc}
                          </p>
                        </div>
                      </li>
                    </Reveal>
                  ))}
                </ol>
              </div>
            </div>
          </div>
        </section>
      )}

      {ind.platformFeatures && ind.platformFeatures.length > 0 && (
        <section className="bg-white py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ Platform features ]"
                title={
                  <>
                    The platform that{" "}
                    <span className="text-flame">runs it.</span>
                  </>
                }
                lead="Three feature pillars that move learning from content delivery to outcome engineering."
                align="center"
              />
            </Reveal>
            <div className="mt-12 grid gap-8 md:grid-cols-3">
              {ind.platformFeatures.map((f, i) => {
                const Icon = f.icon;
                return (
                  <Reveal key={f.title} delay={Math.min(i * 0.07, 0.3)}>
                    <div className="card-lift h-full rounded-2xl border border-line bg-shade p-8 text-center hover:border-flame/40 hover:shadow-lift">
                      {Icon && (
                        <span className="mx-auto flex size-16 items-center justify-center rounded-full bg-flame/10 text-flame">
                          <Icon aria-hidden className="size-7" />
                        </span>
                      )}
                      <p className="mt-5 text-lg font-bold text-ink">
                        {f.title}
                      </p>
                      <p className="mt-2 text-sm leading-relaxed text-body">
                        {f.desc}
                      </p>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>
      )}
    </>
  );
}

/* ---------- Logistics: horizontal 5-node flow with connector lines +
 *  tech-enabler chips strip. Operational, "in motion" feel. ---------- */
function LogisticsShowcase({ ind }: { ind: Industry }) {
  if (!ind.flow && !ind.techEnablers) return null;
  return (
    <>
      {ind.flow && ind.flow.length > 0 && (
        <section className="bg-ink py-section-md text-white">
          <div className="container-site">
            <Reveal>
              <span className="section-label !text-brand-light">
                [ Supply-chain flow ]
              </span>
              <div
                aria-hidden
                className="rule-flame mt-3 mb-6"
              />
              <h2 className="text-display-md font-bold leading-snug text-white">
                Five stages, end-to-end{" "}
                <span className="text-flame">observable.</span>
              </h2>
              <p className="mt-5 max-w-2xl text-[16px] leading-relaxed text-white/70">
                Source, make, store, move, deliver — every node instrumented and recoverable in real time.
              </p>
            </Reveal>

            {/* Horizontal flow with connector arrows */}
            <div className="mt-12 grid gap-2 lg:grid-cols-9 lg:items-center">
              {ind.flow.map((step, i) => {
                const Icon = step.icon;
                return (
                  <Reveal
                    key={step.label}
                    delay={Math.min(i * 0.08, 0.4)}
                    className={
                      // 5 nodes + 4 connectors = 9 cells; nodes at 1,3,5,7,9
                      i === 0
                        ? "lg:col-span-1 lg:col-start-1"
                        : "lg:col-span-1"
                    }
                  >
                    <div className="flex flex-col items-center text-center">
                      <div className="relative">
                        <span className="flex size-16 items-center justify-center rounded-2xl border border-white/20 bg-white/5 text-flame backdrop-blur">
                          {Icon && <Icon aria-hidden className="size-7" />}
                        </span>
                        <span className="absolute -right-1 -top-1 flex size-6 items-center justify-center rounded-full bg-flame font-mono text-xs font-bold text-white">
                          {i + 1}
                        </span>
                      </div>
                      <p className="mt-3 text-sm font-bold text-white">
                        {step.label}
                      </p>
                      <p className="mt-1 text-xs leading-tight text-white/60">
                        {step.desc}
                      </p>
                    </div>
                  </Reveal>
                );
              })}
            </div>
            {/* Connector line under the flow (desktop) */}
            <div
              aria-hidden
              className="mt-2 hidden h-px w-full bg-gradient-to-r from-flame/0 via-flame/40 to-flame/0 lg:block"
            />
          </div>
        </section>
      )}

      {ind.techEnablers && ind.techEnablers.length > 0 && (
        <section className="bg-shade py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ Tech enablers ]"
                title={
                  <>
                    The stack that{" "}
                    <span className="text-flame">powers it.</span>
                  </>
                }
                lead="Six tech enablers we deploy across the supply chain to keep data, identity and provenance trustworthy end-to-end."
                align="center"
              />
            </Reveal>
            <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
              {ind.techEnablers.map((t) => {
                const Icon = t.icon;
                return (
                  <div
                    key={t.name}
                    className="group inline-flex items-center gap-3 rounded-full border border-line bg-white px-5 py-3 transition-all hover:border-flame hover:shadow-float"
                  >
                    {Icon && (
                      <Icon
                        aria-hidden
                        className="size-5 text-brand transition-colors group-hover:text-flame"
                      />
                    )}
                    <div className="flex flex-col">
                      <span className="text-sm font-bold text-ink">
                        {t.name}
                      </span>
                      <span className="text-[11px] leading-tight text-body">
                        {t.desc}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      )}
    </>
  );
}

/* ---------- Cybersecurity: 5 stacked defense layers with coverage
 *  progress bars. Reads as "defense in depth", distinct from any
 *  other industry. ---------- */
function CybersecurityShowcase({ ind }: { ind: Industry }) {
  if (!ind.layers) return null;
  return (
    <section className="bg-shade py-section-md">
      <div className="container-site">
        <Reveal>
          <SectionHeading
            label="[ Defense layers ]"
            title={
              <>
                Five layers,{" "}
                <span className="text-flame">defense in depth.</span>
              </>
            }
            lead="From network edge to human firewall — each layer with its own coverage metric."
            align="center"
          />
        </Reveal>
        <div className="mt-12 space-y-3">
          {ind.layers.map((l, i) => {
            const Icon = l.icon;
            return (
              <Reveal key={l.title} delay={Math.min(i * 0.06, 0.3)}>
                <div className="grid gap-4 rounded-2xl border border-line bg-white p-5 lg:grid-cols-[0.6fr_2fr_1.2fr] lg:items-center lg:gap-6">
                  {/* Icon + number */}
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-xs font-bold tracking-[0.12em] text-ink/40">
                      L{String(i + 1).padStart(2, "0")}
                    </span>
                    {Icon && (
                      <span className="flex size-10 items-center justify-center rounded-lg border border-brand/20 bg-cream text-brand">
                        <Icon aria-hidden className="size-5" />
                      </span>
                    )}
                    <p className="text-base font-bold text-ink">{l.title}</p>
                  </div>
                  {/* Desc */}
                  <p className="text-sm leading-relaxed text-body">
                    {l.desc}
                  </p>
                  {/* Coverage bar */}
                  <div className="flex items-center gap-3">
                    <div className="relative h-2 flex-1 overflow-hidden rounded-full bg-shade">
                      <div
                        className="h-full rounded-full bg-gradient-to-r from-flame to-flame-soft"
                        style={{ width: `${l.coverage}%` }}
                      />
                    </div>
                    <span className="font-mono text-sm font-bold text-flame">
                      {l.coverage}%
                    </span>
                  </div>
                </div>
              </Reveal>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ---------- Ecommerce: omnichannel chips strip + KPI metrics band.
 *  "Conversion + commerce" feel — bright, conversion-focused. ---------- */
function EcommerceShowcase({ ind }: { ind: Industry }) {
  return (
    <>
      {ind.channels && ind.channels.length > 0 && (
        <section className="bg-white py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ Omnichannel ]"
                title={
                  <>
                    One brand,{" "}
                    <span className="text-flame">every channel.</span>
                  </>
                }
                lead="Web, mobile, marketplace, POS, social, voice — inventory and pricing sync across every touchpoint."
                align="center"
              />
            </Reveal>
            <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
              {ind.channels.map((c) => {
                const Icon = c.icon;
                return (
                  <div
                    key={c.label}
                    className="inline-flex items-center gap-2.5 rounded-full border border-line bg-shade px-5 py-2.5"
                  >
                    {Icon && (
                      <Icon aria-hidden className="size-4 text-brand" />
                    )}
                    <span className="text-sm font-semibold text-ink">
                      {c.label}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {ind.ecommerceMetrics && ind.ecommerceMetrics.length > 0 && (
        <section className="bg-ink py-section-md">
          <div className="container-site">
            <Reveal>
              <span className="section-label !text-brand-light">
                [ Commerce KPIs ]
              </span>
              <div aria-hidden className="rule-flame mt-3 mb-6" />
              <h2 className="text-display-md font-bold leading-snug text-white">
                The metrics we{" "}
                <span className="text-flame">move.</span>
              </h2>
            </Reveal>
            <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {ind.ecommerceMetrics.map((m, i) => (
                <Reveal key={m.label} delay={Math.min(i * 0.06, 0.3)}>
                  <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur transition-colors hover:border-flame/40">
                    <p className="text-display-sm font-bold text-flame">
                      {m.value}
                    </p>
                    <p className="mt-2 text-sm font-semibold text-white">
                      {m.label}
                    </p>
                    {m.trend && (
                      <p className="mt-1 font-mono text-xs text-white/50">
                        {m.trend}
                      </p>
                    )}
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>
      )}
    </>
  );
}

/* ---------- Automation: 5-step horizontal workflow with connector
 *  arrows. "Trigger → decide → act → monitor → optimize" feel. ---------- */
function AutomationShowcase({ ind }: { ind: Industry }) {
  if (!ind.workflow) return null;
  return (
    <section className="bg-shade py-section-md">
      <div className="container-site">
        <Reveal>
          <SectionHeading
            label="[ Automation loop ]"
            title={
              <>
                Trigger → decide → act → monitor →{" "}
                <span className="text-flame">optimize.</span>
              </>
            }
            lead="A closed-loop automation workflow that tunes itself with every cycle."
            align="center"
          />
        </Reveal>
        <div className="mt-12 grid gap-4 lg:grid-cols-5 lg:items-stretch">
          {ind.workflow.map((step, i) => {
            const Icon = step.icon;
            const isLast = i === ind.workflow!.length - 1;
            return (
              <Reveal key={step.label} delay={Math.min(i * 0.08, 0.4)}>
                <div className="relative flex h-full flex-col rounded-2xl border border-line bg-white p-6 hover:border-flame/40 hover:shadow-lift">
                  {/* Connector arrow (between cards, desktop only) */}
                  {!isLast && (
                    <span
                      aria-hidden
                      className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 items-center justify-center lg:flex"
                    >
                      <span className="flex size-6 items-center justify-center rounded-full bg-flame text-white shadow-glow-flame">
                        <ArrowRight aria-hidden className="size-3" />
                      </span>
                    </span>
                  )}
                  <div className="flex items-center justify-between">
                    {Icon && (
                      <span className="flex size-12 items-center justify-center rounded-xl border border-brand/20 bg-cream text-brand">
                        <Icon aria-hidden className="size-6" />
                      </span>
                    )}
                    <span className="font-mono text-xs font-bold tracking-[0.12em] text-ink/40">
                      STEP {String(i + 1).padStart(2, "0")}
                    </span>
                  </div>
                  <p className="mt-4 text-base font-bold text-ink">
                    {step.label}
                  </p>
                  <p className="mt-1.5 text-xs leading-relaxed text-body">
                    {step.desc}
                  </p>
                </div>
              </Reveal>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ============================================================
 * LAYOUT A — financial-services · logistics · automation
 *
 *   §1 white  · 2-col sticky intro + offset-cream framed bannerImage
 *   §2 shade  · 4-col KPI / stage cards with flame rules
 *   §3 white  · narrative sections (alternating bg-white/bg-shade)
 *   §4 navy   · glass cards (subIndustries / techEnablers)
 *   §5 white  · "Other industries"
 * ============================================================ */
function LayoutA({ ind }: { ind: Industry }) {
  const Icon = ind.icon;
  const stageData = ind.flow ?? ind.workflow; // logistics.flow / automation.workflow
  const glassData = ind.subIndustries?.items ?? ind.techEnablers;

  return (
    <>
      {/* === §1 — white, 2-col sticky intro + offset-cream framed image === */}
      <section className="bg-white py-section-md">
        <div className="container-site">
          <div className="grid gap-12 lg:grid-cols-[1fr_1.05fr] lg:items-start lg:gap-16">
            {/* Left — sticky intro */}
            <div className="lg:sticky lg:top-32 lg:self-start">
              <Reveal>
                <div className="flex items-center gap-4">
                  {Icon && (
                    <span className="flex size-14 items-center justify-center rounded-xl border border-brand/20 bg-cream text-brand">
                      <Icon aria-hidden className="size-7" />
                    </span>
                  )}
                  <span className="font-mono text-xs font-semibold tracking-[0.12em] text-ink/45">
                    Industry · {ind.title}
                  </span>
                </div>
                <div aria-hidden className="rule-flame mt-6" />
                <span className="section-label">[ {ind.label ?? ind.title} ]</span>
                <h2 className="text-display-lg font-bold leading-[1.1] text-ink">
                  {ind.heroHeading ?? ind.title}
                </h2>
                {ind.intro && (
                  <p className="mt-6 text-[16px] leading-relaxed text-body">
                    {ind.intro}
                  </p>
                )}
                {ind.focusAreas && ind.focusAreas.length > 0 && (
                  <ul className="mt-6 flex flex-wrap gap-2">
                    {ind.focusAreas.map((fa) => (
                      <li
                        key={fa}
                        className="rounded-full border border-brand/30 bg-cream px-3.5 py-1.5 text-xs font-semibold text-brand"
                      >
                        {fa}
                      </li>
                    ))}
                  </ul>
                )}
                <GlobalReachBadge className="mt-6" />
              </Reveal>
            </div>

            {/* Right — bannerImage in offset cream frame */}
            {ind.bannerImage && (
              <Reveal delay={0.1}>
                <div className="relative">
                  <div
                    aria-hidden
                    className="absolute -left-5 -top-5 hidden h-full w-full rounded-2xl border border-line bg-cream lg:block"
                  />
                  <div className="relative overflow-hidden rounded-2xl border border-line bg-ink shadow-lift">
                    <Image
                      src={ind.bannerImage}
                      alt={ind.title}
                      width={760}
                      height={560}
                      sizes="(min-width: 1024px) 760px, 100vw"
                      className="h-[320px] w-full object-cover sm:h-[420px] lg:h-[560px]"
                    />
                    <div
                      aria-hidden
                      className="absolute inset-x-0 bottom-0 h-24"
                      style={{
                        background:
                          "linear-gradient(to top, rgba(11,22,94,0.55) 0%, rgba(11,22,94,0) 100%)",
                      }}
                    />
                  </div>
                </div>
              </Reveal>
            )}
          </div>
        </div>
      </section>

      {/* === §2 — shade, stage cards (flow/workflow only, NOT stats) === */}
      {stageData && stageData.length > 0 && (
        <section className="bg-shade py-section-md">
          <div className="container-site">
            <Reveal>
              <SectionHeading
                label="[ The stages ]"
                title={
                  <>
                    Stages that <span className="text-flame">connect.</span>
                  </>
                }
                lead="Five stages that move work end-to-end — each one observable, instrumented and recoverable in real time."
                align="center"
              />
            </Reveal>

            {/* Stage cards (logistics.flow / automation.workflow) */}
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
              {stageData.map((step, i) => {
                const StepIcon = step.icon;
                const stepLabel = step.label;
                return (
                  <Reveal key={stepLabel + i} delay={Math.min(i * 0.05, 0.3)}>
                    <div className="card-lift relative flex h-full flex-col rounded-2xl border border-line bg-white p-5 hover:border-flame/40 hover:shadow-lift">
                      <div className="flex items-center justify-between">
                        {StepIcon && (
                          <span className="flex size-10 items-center justify-center rounded-lg border border-brand/20 bg-cream text-brand">
                            <StepIcon aria-hidden className="size-5" />
                          </span>
                        )}
                        <span className="font-mono text-xs font-semibold tracking-[0.12em] text-ink/45">
                          {String(i + 1).padStart(2, "0")}
                        </span>
                      </div>
                      <p className="mt-4 text-base font-bold text-ink">
                        {stepLabel}
                      </p>
                      <p className="mt-1 text-xs leading-relaxed text-body">
                          {step.desc}
                        </p>
                      </div>
                    </Reveal>
                  );
                })}
              </div>
          </div>
        </section>
      )}

      {/* === §3 — narrative sections (alternating bg-white/bg-shade, para left + image right) === */}
      {ind.sections?.map((sec, i) => (
        <NarrativeSection
          key={i}
          sec={sec}
          bg={i % 2 === 0 ? "bg-white" : "bg-shade"}
          image={ind.bannerImage}
          imageSide={i % 2 === 0 ? "right" : "left"}
        />
      ))}

      {/* === §4 — ink navy, glass cards (subIndustries / techEnablers) === */}
      {glassData && glassData.length > 0 && (
        <section className="ink-gradient relative overflow-hidden py-section-md">
          <div aria-hidden className="absolute inset-0 grid-pattern opacity-20" />
          <div
            aria-hidden
            className="pointer-events-none absolute -left-20 -top-24 size-64 rounded-full bg-flame/20 blur-3xl"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute -bottom-28 -right-16 size-72 rounded-full bg-flame/15 blur-3xl"
          />
          <div className="container-site relative">
            <Reveal>
              <SectionHeading
                label={
                  ind.subIndustries
                    ? `[ ${ind.subIndustries.heading} ]`
                    : "[ Tech enablers ]"
                }
                title={
                  ind.subIndustries ? (
                    <>
                      Engagements that <span className="text-flame">scale.</span>
                    </>
                  ) : (
                    <>
                      The stack that <span className="text-flame">powers it.</span>
                    </>
                  )
                }
                lead={
                  ind.subIndustries
                    ? "Three flagship service tracks inside this industry — each one scoped, engineered and shipped against a clear business outcome."
                    : "The technologies that make every shipment visible, every contract provable, and every cycle tunable."
                }
                tone="dark"
                align="center"
              />
            </Reveal>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {glassData.map((item, i) => {
                const TIcon = "icon" in item ? item.icon : undefined;
                const itemTitle =
                  "title" in item
                    ? item.title
                    : "name" in item
                      ? item.name
                      : "label" in item
                        ? item.label
                        : "";
                const itemDesc = "desc" in item ? item.desc : "";
                const itemImage = "image" in item ? item.image : undefined;
                return (
                  <Reveal key={itemTitle + i} delay={Math.min(i * 0.07, 0.3)}>
                    <div className="card-lift group relative flex h-full flex-col overflow-hidden rounded-2xl border border-white/15 bg-white/[0.04] backdrop-blur-sm hover:border-flame/40">
                      <span
                        aria-hidden
                        className="absolute inset-x-0 top-0 h-[3px] origin-left scale-x-0 bg-gradient-to-r from-flame to-flame-soft transition-transform duration-500 ease-out-expo group-hover:scale-x-100"
                      />
                      {itemImage && (
                        <div className="relative h-40 overflow-hidden">
                          <Image
                            src={itemImage}
                            alt={itemTitle}
                            fill
                            className="object-cover transition-transform duration-500 ease-out-expo group-hover:scale-105"
                          />
                          <div
                            aria-hidden
                            className="absolute inset-0"
                            style={{
                              background:
                                "linear-gradient(to top, rgba(0,3,61,0.92) 0%, rgba(0,3,61,0.25) 60%, rgba(0,3,61,0) 100%)",
                            }}
                          />
                          <h3 className="absolute bottom-3 left-4 right-4 text-base font-bold leading-snug text-white">
                            {itemTitle}
                          </h3>
                        </div>
                      )}
                      <div className="flex flex-1 flex-col p-6">
                        {!itemImage && TIcon && (
                          <span className="flex size-12 items-center justify-center rounded-xl border border-brand/30 bg-brand/10 text-flame">
                            <TIcon aria-hidden className="size-6" />
                          </span>
                        )}
                        {!itemImage && (
                          <h3 className="mt-4 text-base font-bold leading-snug text-white">
                            {itemTitle}
                          </h3>
                        )}
                        {itemDesc && (
                          <p
                            className={`text-sm leading-relaxed text-white/70 ${
                              itemImage ? "pt-1" : "mt-2"
                            }`}
                          >
                            {itemDesc}
                          </p>
                        )}
                      </div>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>
      )}

    </>
  );
}


/* ============================================================
 * LAYOUT B — healthcare · education · logistics · cybersecurity ·
 * ecommerce · automation (clean editorial template)
 *
 *   §1 white  · 2-col intro (eyebrow + heading + paragraph +
 *                  focusAreas line + GlobalReachBadge) +
 *                  offset-cream framed bannerImage.
 *   §2 shade↔white · ind.sections rendered as paragraph-only
 *                  prose (heading + paragraphs + optional image —
 *                  NO bullets, NO lists). Alternates bg-shade /
 *                  bg-white when multiple sections exist. Falls
 *                  back to a single intro+tagline prose block
 *                  when ind.sections is empty (e.g. automation).
 *   §3 white  · cards grid (subIndustries → pillars →
 *                  platformFeatures → layers → channels →
 *                  flow → workflow → journey fallback chain).
 *                  Each card: icon tile (or numbered tile when
 *                  the item has no icon, e.g. subIndustries
 *                  items) + title + paragraph desc. NO bullets.
 *   §4 full-width banner image break with navy gradient overlay
 *                  + flame rule + tagline quote + GlobalReach
 *                  caption with ArrowRight flourish.
 *
 * No CTA, no "Other industries" footer — ends on the image
 * break so every industry reads the same editorial rhythm.
 * ============================================================ */
function LayoutB({
  ind,
  challengesVariant = "cards-icons",
}: {
  ind: Industry;
  challengesVariant?: "cards-icons" | "split-photo" | "stat-led";
}) {
  // §3 — pick the first available card dataset following the spec
  // fallback chain. The flow / workflow / journey fallbacks are
  // appended so industries like logistics (which only has `flow`)
  // and automation (subIndustries items have no icon, image paths
  // broken — handled by skipping item.image and using a numbered
  // tile) still get a cards section.
  type CardItem = { icon?: LucideIcon; title: string; desc?: string };
  type CardsConfig = {
    items: CardItem[];
    label: string;
    title: ReactNode;
    lead: string;
  };

  const cards: CardsConfig | null = (() => {
    if (ind.subIndustries && ind.subIndustries.items.length > 0) {
      return {
        items: ind.subIndustries.items.map((it) => ({
          title: it.title,
          desc: it.desc,
        })),
        label: `[ ${ind.subIndustries.heading} ]`,
        title: (
          <>
            Engagements that <span className="text-flame">scale.</span>
          </>
        ),
        lead:
          "A focused set of service tracks inside this industry — each one scoped, engineered and shipped against a clear business outcome across the UK, Canada, Dubai and beyond.",
      };
    }
    if (ind.pillars && ind.pillars.length > 0) {
      return {
        items: ind.pillars.map(({ icon, title, desc }) => ({
          icon,
          title,
          desc,
        })),
        label: "[ Care pillars ]",
        title: (
          <>
            Pillars of <span className="text-flame">modern care.</span>
          </>
        ),
        lead:
          "Every engagement is built on these pillars — audited against outcomes, not transactions.",
      };
    }
    if (ind.platformFeatures && ind.platformFeatures.length > 0) {
      return {
        items: ind.platformFeatures.map(({ icon, title, desc }) => ({
          icon,
          title,
          desc,
        })),
        label: "[ Platform features ]",
        title: (
          <>
            Built for <span className="text-flame">scale.</span>
          </>
        ),
        lead:
          "The platform capabilities that make every program measurable, scalable, and resilient across regions, devices and cohorts.",
      };
    }
    if (ind.layers && ind.layers.length > 0) {
      return {
        items: ind.layers.map(({ icon, title, desc }) => ({
          icon,
          title,
          desc,
        })),
        label: "[ Defense layers ]",
        title: (
          <>
            Defense-in-depth,{" "}
            <span className="text-flame">edge to human.</span>
          </>
        ),
        lead:
          "Defensive layers compound into full-spectrum resilience — every layer instrumented, every coverage gap measured and closed.",
      };
    }
    if (ind.channels && ind.channels.length > 0) {
      return {
        items: ind.channels.map(({ icon, label }) => ({
          icon,
          title: label,
        })),
        label: "[ Omnichannel ]",
        title: (
          <>
            Every touchpoint,{" "}
            <span className="text-flame">one experience.</span>
          </>
        ),
        lead:
          "A converged commerce spine across every customer surface — unified inventory, identity, pricing and insight.",
      };
    }
    if (ind.flow && ind.flow.length > 0) {
      return {
        items: ind.flow.map(({ icon, label, desc }) => ({
          icon,
          title: label,
          desc,
        })),
        label: "[ The stages ]",
        title: (
          <>
            Stages that <span className="text-flame">connect.</span>
          </>
        ),
        lead:
          "End-to-end stages that move work through the chain — each one observable, instrumented and recoverable in real time.",
      };
    }
    if (ind.workflow && ind.workflow.length > 0) {
      return {
        items: ind.workflow.map(({ icon, label, desc }) => ({
          icon,
          title: label,
          desc,
        })),
        label: "[ Workflow ]",
        title: (
          <>
            A closed loop that{" "}
            <span className="text-flame">learns.</span>
          </>
        ),
        lead:
          "Five workflow stages that take manual effort out of every cycle — trigger, decide, act, monitor, optimize.",
      };
    }
    if (ind.journey && ind.journey.length > 0) {
      return {
        items: ind.journey.map(({ icon, title, desc }) => ({
          icon,
          title,
          desc,
        })),
        label: "[ Patient journey ]",
        title: (
          <>
            From schedule to{" "}
            <span className="text-flame">recovery.</span>
          </>
        ),
        lead:
          "The patient journey, reimagined around outcomes — every step instrumented, every handoff accountable, every recovery visible.",
      };
    }
    return null;
  })();

  // §2 — prose sections: ind.sections, or a single fallback section
  // synthesized from intro + tagline when ind.sections is empty
  // (e.g. automation has no `sections` field).
  type ProseSection = NonNullable<Industry["sections"]>[number];
  const proseSections: ProseSection[] =
    ind.sections && ind.sections.length > 0
      ? ind.sections
      : [
          {
            heading: ind.heroHeading ?? ind.title,
            paragraphs: [ind.intro, ind.tagline].filter(
              Boolean
            ) as string[],
          },
        ];

  /* Per-industry prose rhythm — picked by slug so split-hero pages
   * (education, logistics, automation) flip the bg alternation vs.
   * fullbleed-hero pages so §2 reads differently from page to page
   * even when the section template is the same. */
  type BgPattern = "alt-shade-first" | "alt-white-first" | "all-white";
  type ImagePattern = "alternate" | "always-right" | "always-left";
  const PROSE_RHYTHM: Record<string, { bg: BgPattern; img: ImagePattern }> = {
    "financial-services": { bg: "alt-shade-first", img: "alternate" },
    healthcare: { bg: "alt-shade-first", img: "alternate" },
    education: { bg: "alt-white-first", img: "always-right" },
    logistics: { bg: "alt-white-first", img: "always-left" },
    cybersecurity: { bg: "all-white", img: "always-right" },
    ecommerce: { bg: "alt-shade-first", img: "always-right" },
    automation: { bg: "all-white", img: "always-left" },
  };
  const rhythm = PROSE_RHYTHM[ind.slug] ?? {
    bg: "alt-shade-first" as BgPattern,
    img: "alternate" as ImagePattern,
  };
  const bgFor = (i: number): "bg-white" | "bg-shade" => {
    if (rhythm.bg === "all-white") return "bg-white";
    if (rhythm.bg === "alt-white-first")
      return i % 2 === 0 ? "bg-white" : "bg-shade";
    return i % 2 === 0 ? "bg-shade" : "bg-white";
  };
  const sideFor = (i: number): "left" | "right" => {
    if (rhythm.img === "always-right") return "right";
    if (rhythm.img === "always-left") return "left";
    return i % 2 === 0 ? "right" : "left";
  };

  return (
    <>
      {/* === §1 — Challenges the industry faces =========================
       * Replaces the old text-only intro (which duplicated PageHero).
       * Now uses real industry pain-point data from `ind.challenges`
       * with the per-industry variant picked in CHALLENGES_VARIANTS. === */}
      {ind.challenges && ind.challenges.length > 0 && (
        <ChallengesSection
          challenges={ind.challenges}
          variant={challengesVariant}
          image={ind.bannerImage}
        />
      )}

      {/* === §2 — prose sections (per-industry bg + image-side rhythm
       * so no two industry pages feel identical) === */}
      {proseSections.map((sec, i) => (
        <NarrativeSection
          key={i}
          sec={sec}
          bg={bgFor(i)}
          image={ind.bannerImage}
          imageSide={sideFor(i)}
        />
      ))}

      {/* === §2.5 — Per-industry UNIQUE showcase module ===================
       * Each industry has its own showcase data shape (pillars, journey,
       * pathway, platformFeatures, flow, techEnablers, layers, channels,
       * ecommerceMetrics, workflow). Rendering it here gives every page
       * a visibly different body section that no sibling page has.
       * === */}
      <IndustryShowcase ind={ind} />

      {/* === §3 — white, paragraph-based content with image (NOT cards) === */}
      {cards && cards.items.length > 0 && (
        <section className="bg-white py-section-md">
          <div className="container-site">
            <div className="grid gap-12 lg:grid-cols-2 lg:items-start lg:gap-16">
              {/* Left — paragraph */}
              <div>
                <Reveal>
                  <div aria-hidden className="rule-flame mb-6" />
                  <h3 className="text-display-md font-bold leading-snug text-ink">
                    {cards.title}
                  </h3>
                  <div className="mt-5 space-y-4">
                    {cards.items.map((item, i) => (
                      <p key={i} className="text-[16px] leading-relaxed text-body">
                        <span className="font-semibold text-ink">{item.title}</span>
                        {item.desc ? ` — ${item.desc}` : ""}
                      </p>
                    ))}
                  </div>
                </Reveal>
              </div>
              {/* Right — image */}
              {ind.bannerImage && (
                <Reveal delay={0.1}>
                  <div className="relative">
                    <div
                      aria-hidden
                      className="absolute -right-5 -top-5 hidden h-full w-full rounded-2xl border border-line bg-cream lg:block"
                    />
                    <div className="relative overflow-hidden rounded-2xl shadow-float">
                      <Image
                        src={ind.bannerImage}
                        alt={ind.title}
                        width={640}
                        height={480}
                        className="h-[280px] w-full object-cover sm:h-[360px] lg:h-[440px]"
                      />
                    </div>
                  </div>
                </Reveal>
              )}
            </div>
          </div>
        </section>
      )}

    </>
  );
}
